name: fc-ci-sonarcloud

on:
  pull_request:
    branches:
      - master
      
jobs:
  run-fc-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

        with:
          node-version: 14
      - run: jest --coverage

      #- name: SonarCloud Scan
        #uses: SonarSource/sonarcloud-github-action@master
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}